<h3>Your profile</h3>


<dl>
    <dt>Name<dt>
    <dd><?php echo $profile->getFirstname();?></dd>
    <dt>Surname<dt>
    <dd><?php echo $profile->getSurname();?></dd>
    <dt>Email<dt>
    <dd><?php echo $profile->getEmail();?></dd>
</dl>

<?php if ($this->umsAuthentication() !== false && $this->umsAuthentication()->getIs_admin()== 1): ?> 
<?php $url = $this->url('memo', array('id' => $this->umsAuthentication()->getId())); ?>

<h4>Notities</h4>
<a href="<?php echo $url;?>">Add note</a>



<?php endif ?>