<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
        ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">

            <h3> hello <?php if ($this->umsAuthentication() !== false): ?> 
                    <?php echo $this->umsAuthentication()->getFirstname(); ?>
<?php endif ?>
            </h3> 

<?php if ($this->umsAuthentication() !== false): ?> 
                <a href="<?php echo $this->url('profile') ?>">Profiel</a><br/>    
                <a href="<?php echo $this->url('logout') ?>">Uitloggen</a>
                <br/>
            <?php endif ?>
                
              
            <?php if ($this->umsAuthentication() !== false && $this->umsAuthentication()->getIs_admin() == 1) : ?>
                <h5>Admin Functies</h5>
                <a href="<?php echo $this->url('users') ?>">Bekijk alle users</a>
            <?php endif ?>    
                <?php if ($this->flashMessenger()->hasMessages()) : ?>
                <div class="messages">			
                    <?php foreach ($this->flashMessenger()->getMessages() as $message) : ?>
                        <div class="alert"><?php echo $message ?></div>
                <?php endforeach ?>
                </div>
<?php endif ?>




<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; </p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
